name: 'Scope for Javascript'
author: 'Undefined Labs'
description: 'Automatically instruments and runs your tests using the Scope Javascript agent.'
inputs:
  command:
    description: 'Command to run your tests.'
    required: false
    default: 'npm test'
  command-cypress:
    description: 'Command to run your cypress tests.'
    required: false
  cypress-endpoint:
    description: 'URL to run the cypress tests against.'
    required: false
    default: 'http://localhost:3000'
  dsn:
    description: 'Scope DSN'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'check-square'
  color: 'purple'
